FROM quay.io/fedora-ostree-desktops/base:39

COPY files/ /
COPY scripts/ /scripts
COPY environment /etc
ADD certs/public_key.der /etc/pki/akmods/certs/public_key.der
ADD certs/private_key.priv /etc/pki/akmods/private/private_key.priv

RUN chmod +x /scripts/*
#RUN /scripts/add-repos.sh
#
#RUN /scripts/common.sh
#
#RUN /scripts/fusion.sh
#
#RUN /scripts/nvidia.sh
#
#RUN /scripts/hypr.sh
#
#RUN /scripts/disable-repos.sh

RUN for script in add-repos common fusion nvidia hypr disable-repos; \
    do \
        /scripts/$script.sh; \
        /scripts/cleanup.sh $script; \
    done

RUN rm -rf /tmp/* /var/* && \
    ostree container commit
