FROM quay.io/fedora/fedora-coreos:next

COPY files/ /
COPY scripts/ /tmp/scripts
COPY environment /etc
ADD certs/public_key.der /etc/pki/akmods/certs/public_key.der
ADD certs/private_key.priv /etc/pki/akmods/private/private_key.priv

RUN chmod +x /tmp/scripts/*
RUN rpm-ostree install wget

RUN /tmp/scripts/add-repos.sh

RUN /tmp/scripts/common.sh

RUN /tmp/scripts/nvidia.sh

RUN /tmp/scripts/core.sh

RUN /tmp/scripts/hypr.sh

RUN /tmp/scripts/disable-repos.sh

RUN rm -rf /tmp/* /var/* && \
    ostree container commit
