FROM quay.io/fedora/fedora-silverblue:latest

COPY files/ /
COPY scripts/ /scripts
COPY environment /etc
ADD certs/public_key.der /etc/pki/akmods/certs/public_key.der
ADD certs/private_key.priv /etc/pki/akmods/private/private_key.priv

RUN chmod +x /scripts/*
RUN /scripts/add-repos.sh

RUN /scripts/common.sh

RUN /scripts/fusion.sh

RUN /scripts/nvidia.sh

RUN /scripts/gnome.sh

RUN /scripts/disable-repos.sh

RUN rm -rf /tmp/* /var/* && \
    ostree container commit
