FROM quay.io/fedora/fedora-coreos:next

COPY files/ /
COPY scripts/ /tmp/scripts

RUN chmod +x /tmp/scripts/*
RUN /tmp/scripts/coreos-util.sh

RUN /tmp/scripts/add-repos.sh

RUN /tmp/scripts/common.sh

RUN /tmp/scripts/amdel.sh

RUN /tmp/scripts/hypr.sh

RUN /tmp/scripts/disable-repos.sh

RUN rm -rf /tmp/* /var/* && \
    ostree container commit
