FROM quay.io/fedora/fedora-silverblue:latest

COPY files/ /
COPY scripts/ /scripts

RUN chmod +x /scripts/*
#RUN /scripts/add-repos.sh
#
#RUN /scripts/common.sh
#
#RUN /scripts/fusion.sh
#
#RUN /scripts/amdel.sh
#
#RUN /scripts/gnome.sh
#
#RUN /scripts/disable-repos.sh

RUN for script in add-repos common fusion amdel gnome disable-repos; \
    do \
        /scripts/$script.sh; \
        /scripts/cleanup.sh $script; \
    done


RUN rm -rf /tmp/* /var/* && \
    ostree container commit
