FROM quay.io/fedora-ostree-desktops/base:39

COPY files/ /
COPY scripts/ /scripts

RUN chmod +x /scripts/*
#RUN /scripts/add-repos.sh
#
#RUN /scripts/common.sh
#
#RUN /scripts/amdel.sh
#
#RUN /scripts/fusion.sh
#
#RUN /scripts/hypr.sh
#
#RUN /scripts/disable-repos.sh

RUN for script in add-repos common fusion amdel hypr disable-repos; \
    do \
        /scripts/$script.sh; \
        /scripts/cleanup.sh $script; \
    done

RUN rm -rf /tmp/* /var/* /scripts && \
    ostree container commit
