FROM quay.io/fedora/fedora-kinoite:40

COPY files/ /

RUN ./scripts/common.sh

RUN ./scripts/fusion.sh

RUN ./scripts/nvidia.sh

RUN ./scripts/kde.sh

RUN rm -rf /tmp/* /var/* && \
    ostree container commit
