FROM quay.io/fedora/fedora-silverblue:latest

COPY files/ /
COPY scripts/ /scripts

RUN chmod +x /scripts/*
RUN /scripts/add-repos.sh

RUN /scripts/common.sh

RUN /scripts/fusion.sh

RUN /scripts/amdel.sh

RUN /scripts/gnome.sh

RUN /scripts/disable-repos.sh

RUN rm -rf /tmp/* /var/* && \
    ostree container commit
