FROM quay.io/fedora/fedora-kinoite:40

COPY files/ /
COPY scripts/ /tmp/scripts
COPY environment /etc
ADD certs/public_key.der /etc/pki/akmods/certs/public_key.der
ADD certs/private_key.priv /etc/pki/akmods/private/private_key.priv

RUN chmod +x /tmp/scripts/*
RUN /tmp/scripts/common.sh

RUN /tmp/scripts/fusion.sh

RUN /tmp/scripts/nvidia.sh

RUN /tmp/scripts/kde.sh

RUN rm -rf /tmp/* /var/* && \
    ostree container commit
