#!/usr/bin/env bash

VER=1
VER_FILE="/etc/timesink/ver-dot"
VER_RAN=$(cat $VER_FILE)

if [[ -f $VER_FILE && $VER = $VER_RAN ]]; then
    echo "Dotfile manager v$VER has already ran. Exiting..."
    exit 0
fi

rm -rf ~/.config/hypr ~/.config/kitty ~/.config/mako ~/.config/waybar ~/.config/wofi

cp -r /usr/etc/timesink/config/hypr ~/.config/
cp -r /usr/etc/timesink/config/kitty ~/.config/
cp -r /usr/etc/timesink/config/mako ~/.config/
cp -r /usr/etc/timesink/config/waybar ~/.config/
cp -r /usr/etc/timesink/config/wofi ~/.config/

echo $VER > $VER_FILE
