#!/usr/bin/env bash

VER=1
VER_FILE="~/.config/ver-dot"

if [[ ! -f $VER_FILE ]]; then
    touch $VER_FILE
fi

VER_RAN=$(cat $VER_FILE)

if [[ -f $VER_FILE && $VER = $VER_RAN ]]; then
    echo "Dotfile manager v$VER has already ran. Exiting..."
    exit 0
fi

rm -rf ~/.config/hypr ~/.config/kitty ~/.config/mako ~/.config/waybar ~/.config/wofi

cp -r /usr/share/timesink/config/hypr ~/.config/
cp -r /usr/share/timesink/config/kitty ~/.config/
cp -r /usr/share/timesink/config/mako ~/.config/
cp -r /usr/share/timesink/config/waybar ~/.config/
cp -r /usr/share/timesink/config/wofi ~/.config/
cp -r /usr/share/timesink/config/wlogout ~/.config/

echo $VER > $VER_FILE
