on:
  push:
    paths:
      - 'boot_menu.yml'
      - '.github/workflows/release-iso.yml'
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

name: release-iso
jobs:
  release-iso:
    name: Generate and Release ISOs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    container: 
      image: fedora:39
      options: --privileged
      volumes:
        - "/:/host"
    strategy:
      fail-fast: false
      matrix:
        image_name: [timesink-hyprland, timesink-silverblue]
        gpu_name: [nonvidia, nvidia]
        major_version: [39]
        image_tag: [stable]
    steps:
      - name: Generate ISO  
        uses: ublue-os/isogenerator@1.0.9
        id: build
        with:
          ARCH: x86_64
          IMAGE_NAME: ${{ matrix.image_name }}-${{ matrix.gpu_name }}
          IMAGE_REPO: ${{ env.IMAGE_REGISTRY }}
          VARIANT: 'Hyprland'
          VERSION: ${{ matrix.major_version }}
          IMAGE_TAG: ${{ matrix.image_tag }}

      - name: Upload ISO + Checksum
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ matrix.image_name }}-${{ matrix.gpu_name }}-${{ matrix.image_tag }}-${{ matrix.major_version }}
          path: ${{ steps.build.outputs.output-directory }}
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
          overwrite: true
